# Generated by Django 5.1.3 on 2024-12-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=50, unique=True)),
                ('created_by', models.CharField(max_length=255)),
                ('team_leader', models.CharField(max_length=255)),
                ('sales_rep', models.CharField(max_length=255)),
                ('customer_source', models.CharField(max_length=100)),
                ('customer_source_type', models.CharField(max_length=50)),
                ('quote_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('bid_package', models.CharField(max_length=50)),
                ('project_address', models.CharField(max_length=255)),
                ('construction_items', models.CharField(max_length=255)),
                ('brand_name', models.CharField(max_length=50)),
                ('airCondition_type', models.CharField(max_length=50)),
                ('construction_type', models.CharField(max_length=50)),
                ('project_type', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RequestPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=255)),
                ('id_product', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
